name = "vibecheck-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "f5334486112642d8b3f109cfed2af606"

[[d1_databases]]
binding = "DB"
database_name = "vibecheck"
database_id = "ad861c37-485d-4df8-ad15-04a2530d7fa0"

[vars]
FRONTEND_URL = "https://git-vibe.pages.dev"
